import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Plant from '../models/Plant.js';
import User from '../models/User.js';

dotenv.config();

const plants = [
  {
    name: 'Snake Plant',
    price: 499,
    description: 'Hardy, air-purifying plant that thrives on neglect. Perfect for beginners and bedrooms.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 2-3 weeks', sunlightRequirement: 'Low to bright indirect light', soilType: 'Well-draining succulent mix', soilChangeFrequency: 'Every 2 years', temperature: '15-29°C', humidity: '30-50%' },
    stock: 25,
    featured: true,
    ratings: { average: 4.5, count: 128 },
  },
  {
    name: 'Aloe Vera',
    price: 349,
    description: 'A healing succulent with medicinal properties. The gel inside its leaves soothes burns and skin irritations.',
    category: 'succulent',
    isMedicinal: true,
    medicalProperties: { uses: ['Burn relief', 'Skin hydration', 'Digestive aid'], benefits: 'Soothes sunburns, moisturizes skin, and aids digestion when consumed as juice.', partsUsed: 'Leaf gel', dosageInfo: 'Apply gel directly to affected area. For juice: 1 tablespoon daily.', precautions: 'Not recommended for pregnant women internally.' },
    careGuide: { wateringSchedule: 'Every 2-3 weeks', sunlightRequirement: 'Bright indirect light', soilType: 'Well-draining cactus mix', soilChangeFrequency: 'Every 2 years', temperature: '18-27°C', humidity: 'Low' },
    stock: 20,
    featured: true,
    ratings: { average: 4.7, count: 95 },
  },
  {
    name: 'Monstera Deliciosa',
    price: 899,
    description: 'Iconic split-leaf tropical plant that makes a bold statement. Known for its large, fenestrated leaves.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Bright indirect light', soilType: 'Rich, well-draining potting mix', soilChangeFrequency: 'Every 12-18 months', temperature: '18-27°C', humidity: '60-80%' },
    stock: 10,
    featured: true,
    ratings: { average: 4.8, count: 67 },
  },
  {
    name: 'Lavender',
    price: 299,
    description: 'Fragrant purple blooms that attract pollinators and calm the mind. A delightful addition to any garden.',
    category: 'outdoor',
    isMedicinal: true,
    medicalProperties: { uses: ['Anxiety relief', 'Sleep aid', 'Antiseptic'], benefits: 'Reduces anxiety, promotes restful sleep, and has natural antiseptic properties.', partsUsed: 'Flowers, essential oil', dosageInfo: 'Aromatherapy: 3-5 drops in diffuser. Tea: 1 tsp dried flowers steeped 5 min.', precautions: 'May cause skin irritation in concentrated form.' },
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Full sun (6+ hours)', soilType: 'Well-draining alkaline soil', soilChangeFrequency: 'Every 2-3 years when repotting', temperature: '15-30°C', humidity: 'Low' },
    stock: 30,
    featured: true,
    ratings: { average: 4.3, count: 82 },
  },
  {
    name: 'Tulsi (Holy Basil)',
    price: 199,
    description: 'Sacred Indian herb with powerful adaptogenic and immune-boosting properties. A staple in every home.',
    category: 'medicinal',
    isMedicinal: true,
    medicalProperties: { uses: ['Immunity boost', 'Stress relief', 'Respiratory health', 'Anti-inflammatory'], benefits: 'Strengthens immunity, reduces stress, supports respiratory health, and reduces inflammation.', partsUsed: 'Leaves, seeds', dosageInfo: 'Tea: 5-7 leaves steeped in hot water for 5 min. Chew 2-3 fresh leaves daily.', precautions: 'May lower blood sugar. Consult doctor if on diabetes medication.' },
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun to partial shade', soilType: 'Well-draining loamy soil', soilChangeFrequency: 'Every 12 months', temperature: '20-38°C', humidity: '40-60%' },
    stock: 35,
    featured: true,
    ratings: { average: 4.9, count: 156 },
  },
  {
    name: 'Peace Lily',
    price: 599,
    description: 'Elegant white blooms and glossy green leaves. One of the best air-purifying plants for indoor spaces.',
    category: 'flowering',
    careGuide: { wateringSchedule: 'Weekly', sunlightRequirement: 'Low to medium indirect light', soilType: 'Moist, well-draining potting mix', soilChangeFrequency: 'Every 12-18 months', temperature: '18-26°C', humidity: '50-70%' },
    stock: 15,
    featured: true,
    ratings: { average: 4.6, count: 73 },
  },
  {
    name: 'Jade Plant',
    price: 449,
    description: 'Lucky money plant with thick, oval-shaped leaves. A symbol of prosperity and good fortune.',
    category: 'succulent',
    careGuide: { wateringSchedule: 'Every 2-4 weeks', sunlightRequirement: 'Bright indirect to direct light', soilType: 'Well-draining cactus mix', soilChangeFrequency: 'Every 2 years', temperature: '18-27°C', humidity: '30-50%' },
    stock: 18,
    featured: false,
    ratings: { average: 4.4, count: 54 },
  },
  {
    name: 'Rosemary',
    price: 249,
    description: 'Aromatic culinary herb that enhances memory and adds flavor to dishes. A must-have kitchen plant.',
    category: 'medicinal',
    isMedicinal: true,
    medicalProperties: { uses: ['Memory enhancement', 'Digestive aid', 'Hair growth', 'Anti-inflammatory'], benefits: 'Improves memory and concentration, aids digestion, promotes hair growth, and reduces inflammation.', partsUsed: 'Leaves, stems', dosageInfo: 'Tea: 1 tsp dried leaves steeped 5 min. Culinary: add fresh leaves to dishes.', precautions: 'Avoid therapeutic doses during pregnancy.' },
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Full sun (6+ hours)', soilType: 'Well-draining sandy soil', soilChangeFrequency: 'Every 12-18 months', temperature: '15-30°C', humidity: 'Low' },
    stock: 22,
    featured: false,
    ratings: { average: 4.2, count: 48 },
  },
  {
    name: 'Fiddle Leaf Fig',
    price: 1299,
    description: 'The trendiest houseplant with large, violin-shaped leaves. A dramatic focal point for any room.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Bright indirect light', soilType: 'Well-draining potting mix with perlite', soilChangeFrequency: 'Every 12-18 months', temperature: '18-27°C', humidity: '40-60%' },
    stock: 8,
    featured: false,
    ratings: { average: 4.1, count: 36 },
  },
  {
    name: 'Money Plant (Pothos)',
    price: 299,
    description: 'An easy-to-grow trailing plant that brings positive energy according to Vastu and Feng Shui.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Low to bright indirect light', soilType: 'General potting mix', soilChangeFrequency: 'Every 12-18 months', temperature: '17-30°C', humidity: '40-60%' },
    stock: 40,
    featured: false,
    ratings: { average: 4.5, count: 112 },
  },
  {
    name: 'Marigold',
    price: 149,
    description: 'Vibrant orange and yellow flowers that bloom abundantly. Natural pest repellent for gardens.',
    category: 'flowering',
    isMedicinal: true,
    medicalProperties: { uses: ['Skin healing', 'Anti-inflammatory', 'Natural dye'], benefits: 'Promotes wound healing, reduces inflammation, and petals are used as natural food coloring.', partsUsed: 'Flowers, leaves', dosageInfo: 'Calendula ointment: apply topically. Tea: 1 tsp dried petals steeped 10 min.', precautions: 'May cause allergic reactions in sensitive individuals.' },
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun', soilType: 'Well-draining fertile soil', soilChangeFrequency: 'Annual replanting', temperature: '15-35°C', humidity: '40-60%' },
    stock: 50,
    featured: false,
    ratings: { average: 4.0, count: 29 },
  },
  {
    name: 'Bamboo Palm',
    price: 749,
    description: 'An elegant indoor palm that adds a tropical vibe. Excellent air purifier and humidity booster.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Bright indirect to partial shade', soilType: 'Moist, well-draining potting mix', soilChangeFrequency: 'Every 2 years', temperature: '18-26°C', humidity: '50-70%' },
    stock: 12,
    featured: false,
    ratings: { average: 4.3, count: 41 },
  },
  {
    name: 'Neem Plant',
    price: 399,
    description: 'The village pharmacy tree with powerful antibacterial, antifungal, and mosquito-repelling properties.',
    category: 'medicinal',
    isMedicinal: true,
    medicalProperties: { uses: ['Skin care', 'Oral health', 'Mosquito repellent', 'Immune support'], benefits: 'Treats acne and skin conditions, promotes oral health, repels mosquitoes, and boosts immunity.', partsUsed: 'Leaves, bark, oil', dosageInfo: 'Leaf paste: apply to skin. Oil: dilute and apply topically. Do not consume neem oil internally.', precautions: 'Not safe for pregnant women. Do not consume neem oil. Consult doctor before internal use.' },
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Full sun', soilType: 'Well-draining sandy loam', soilChangeFrequency: 'Every 12 months when young', temperature: '20-40°C', humidity: '30-60%' },
    stock: 15,
    featured: false,
    ratings: { average: 4.6, count: 63 },
  },
  {
    name: 'Orchid (Phalaenopsis)',
    price: 999,
    description: 'Exotic moth orchid with long-lasting blooms. A sophisticated gift that flowers for months.',
    category: 'flowering',
    careGuide: { wateringSchedule: 'Every 7-10 days', sunlightRequirement: 'Bright indirect light', soilType: 'Orchid bark mix', soilChangeFrequency: 'Every 1-2 years', temperature: '18-27°C', humidity: '50-70%' },
    stock: 7,
    featured: false,
    ratings: { average: 4.7, count: 58 },
  },
  {
    name: 'Cactus Mix',
    price: 199,
    description: 'A cute, low-maintenance desert plant that thrives on neglect. Perfect deskside companion.',
    category: 'succulent',
    careGuide: { wateringSchedule: 'Every 3-4 weeks', sunlightRequirement: 'Bright direct light', soilType: 'Well-draining cactus mix', soilChangeFrequency: 'Every 3 years', temperature: '15-35°C', humidity: 'Low' },
    stock: 45,
    featured: false,
    ratings: { average: 4.1, count: 34 },
  },
  {
    name: 'ZZ Plant',
    price: 549,
    description: 'Nearly indestructible plant with waxy green leaves. Thrives in low light and neglect — the ultimate beginner plant.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 3-4 weeks', sunlightRequirement: 'Low to bright indirect light', soilType: 'Well-draining potting mix', soilChangeFrequency: 'Every 2 years', temperature: '18-27°C', humidity: '30-50%' },
    stock: 20,
    featured: true,
    ratings: { average: 4.6, count: 89 },
  },
  {
    name: 'Spider Plant',
    price: 349,
    description: 'Classic trailing plant with arching green-and-white leaves. Produces baby spiders that are easy to propagate.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Bright indirect light', soilType: 'General potting mix', soilChangeFrequency: 'Every 12-18 months', temperature: '15-26°C', humidity: '40-60%' },
    stock: 30,
    featured: true,
    ratings: { average: 4.4, count: 72 },
  },
  {
    name: 'Philodendron Brasil',
    price: 449,
    description: 'Heart-shaped leaves with stunning green and lime variegation. Fast-growing trailing beauty for shelves.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Medium to bright indirect light', soilType: 'Well-draining potting mix', soilChangeFrequency: 'Every 12-18 months', temperature: '18-28°C', humidity: '50-70%' },
    stock: 18,
    featured: true,
    ratings: { average: 4.5, count: 48 },
  },
  {
    name: 'Boston Fern',
    price: 399,
    description: 'Lush, feathery fern that adds instant greenery. Loves humidity and looks stunning in hanging baskets.',
    category: 'indoor',
    careGuide: { wateringSchedule: '2-3 times per week', sunlightRequirement: 'Bright indirect light', soilType: 'Moist, well-draining potting mix', soilChangeFrequency: 'Every 12 months', temperature: '16-24°C', humidity: '60-80%' },
    stock: 12,
    featured: false,
    ratings: { average: 4.2, count: 39 },
  },
  {
    name: 'Rubber Plant',
    price: 649,
    description: 'Bold, architectural plant with large glossy burgundy leaves. Makes a striking statement in any room.',
    category: 'indoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Bright indirect light', soilType: 'Well-draining potting mix', soilChangeFrequency: 'Every 12-18 months', temperature: '18-27°C', humidity: '40-60%' },
    stock: 14,
    featured: false,
    ratings: { average: 4.3, count: 44 },
  },
  {
    name: 'Hibiscus',
    price: 449,
    description: 'Tropical beauty with large, showy flowers in vibrant colors. Blooms continuously through warm months.',
    category: 'outdoor',
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun', soilType: 'Rich, well-draining soil', soilChangeFrequency: 'Every 12 months for pots', temperature: '18-32°C', humidity: '50-70%' },
    stock: 16,
    featured: true,
    ratings: { average: 4.5, count: 57 },
  },
  {
    name: 'Bougainvillea',
    price: 549,
    description: 'Drought-tolerant climber with vibrant papery bracts in pink, purple, and orange. Perfect for trellises.',
    category: 'outdoor',
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Full sun (6+ hours)', soilType: 'Well-draining sandy soil', soilChangeFrequency: 'Every 2 years', temperature: '15-35°C', humidity: 'Low' },
    stock: 22,
    featured: true,
    ratings: { average: 4.4, count: 63 },
  },
  {
    name: 'Jasmine (Mogra)',
    price: 299,
    description: 'Fragrant white flowers that fill your garden with enchanting scent. Used in garlands and aromatherapy.',
    category: 'outdoor',
    isMedicinal: true,
    medicalProperties: { uses: ['Stress relief', 'Aromatherapy', 'Skin health'], benefits: 'Reduces stress and anxiety, promotes restful sleep, and improves skin elasticity.', partsUsed: 'Flowers, essential oil', dosageInfo: 'Aromatherapy: 2-3 drops in diffuser. Tea: steep fresh flowers 5 min.', precautions: 'Essential oil must be diluted before topical use.' },
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun to partial shade', soilType: 'Rich, well-draining loamy soil', soilChangeFrequency: 'Every 12 months', temperature: '18-35°C', humidity: '50-70%' },
    stock: 28,
    featured: false,
    ratings: { average: 4.6, count: 81 },
  },
  {
    name: 'Echeveria Succulent',
    price: 249,
    description: 'Rosette-shaped succulent with plump pastel leaves. A stunning addition to any succulent arrangement.',
    category: 'succulent',
    careGuide: { wateringSchedule: 'Every 2-3 weeks', sunlightRequirement: 'Bright direct to indirect light', soilType: 'Well-draining cactus mix', soilChangeFrequency: 'Every 2 years', temperature: '18-28°C', humidity: '30-40%' },
    stock: 35,
    featured: true,
    ratings: { average: 4.3, count: 41 },
  },
  {
    name: 'String of Pearls',
    price: 399,
    description: 'Unique trailing succulent with bead-like leaves. Creates a stunning waterfall effect in hanging pots.',
    category: 'succulent',
    careGuide: { wateringSchedule: 'Every 2-3 weeks', sunlightRequirement: 'Bright indirect light', soilType: 'Well-draining succulent mix', soilChangeFrequency: 'Every 2 years', temperature: '18-27°C', humidity: '40-60%' },
    stock: 14,
    featured: false,
    ratings: { average: 4.7, count: 56 },
  },
  {
    name: 'Ashwagandha',
    price: 349,
    description: 'Powerful adaptogenic herb used in Ayurveda for centuries. Known for reducing stress and boosting vitality.',
    category: 'medicinal',
    isMedicinal: true,
    medicalProperties: { uses: ['Stress reduction', 'Energy boost', 'Thyroid support', 'Cognitive health'], benefits: 'Reduces cortisol levels, improves energy and focus, supports thyroid function, and enhances memory.', partsUsed: 'Root, leaves', dosageInfo: 'Root powder: 1 tsp with warm milk before bed. Capsules: 300-500mg daily.', precautions: 'Avoid if pregnant or with thyroid disorders without medical supervision.' },
    careGuide: { wateringSchedule: 'Every 1-2 weeks', sunlightRequirement: 'Full sun to partial shade', soilType: 'Well-draining sandy loam', soilChangeFrequency: 'Every 12 months', temperature: '20-38°C', humidity: '30-50%' },
    stock: 20,
    featured: true,
    ratings: { average: 4.5, count: 47 },
  },
  {
    name: 'Giloy (Guduchi)',
    price: 249,
    description: 'Immunity-boosting Ayurvedic creeper known as "Amrita" — the root of immortality. Powerful antiviral properties.',
    category: 'medicinal',
    isMedicinal: true,
    medicalProperties: { uses: ['Immunity booster', 'Fever management', 'Liver health', 'Anti-inflammatory'], benefits: 'Strengthens immune system, helps manage chronic fever, supports liver function, and reduces joint inflammation.', partsUsed: 'Stem, leaves', dosageInfo: 'Decoction: boil stem pieces in water for 10 min. Juice: 1-2 tsp daily.', precautions: 'May interact with immunosuppressants. Consult doctor before use.' },
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun to partial shade', soilType: 'Well-draining fertile soil', soilChangeFrequency: 'Every 12 months', temperature: '20-40°C', humidity: '50-70%' },
    stock: 18,
    featured: false,
    ratings: { average: 4.4, count: 38 },
  },
  {
    name: 'Rose Plant',
    price: 399,
    description: 'Classic garden rose with fragrant blooms. Available in red, pink, yellow, and white varieties.',
    category: 'flowering',
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun (6+ hours)', soilType: 'Rich, well-draining loamy soil', soilChangeFrequency: 'Every 12-18 months', temperature: '15-30°C', humidity: '50-70%' },
    stock: 24,
    featured: true,
    ratings: { average: 4.6, count: 93 },
  },
  {
    name: 'Dahlia',
    price: 349,
    description: 'Show-stopping blooms in a rainbow of colors. Flowers range from dinner-plate size to delicate pompons.',
    category: 'flowering',
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Full sun', soilType: 'Rich, well-draining soil', soilChangeFrequency: 'Annual replanting', temperature: '15-28°C', humidity: '40-60%' },
    stock: 12,
    featured: false,
    ratings: { average: 4.3, count: 35 },
  },
  {
    name: 'Sunflower',
    price: 149,
    description: 'Cheerful, fast-growing annual with massive golden flower heads that follow the sun across the sky.',
    category: 'flowering',
    careGuide: { wateringSchedule: 'Every 1-2 days', sunlightRequirement: 'Full sun', soilType: 'Well-draining fertile soil', soilChangeFrequency: 'Annual replanting', temperature: '18-35°C', humidity: '40-50%' },
    stock: 50,
    featured: false,
    ratings: { average: 4.1, count: 27 },
  },
  {
    name: 'Turmeric Plant',
    price: 299,
    description: 'Golden spice plant with powerful anti-inflammatory and antioxidant properties. Grow your own fresh turmeric.',
    category: 'medicinal',
    isMedicinal: true,
    medicalProperties: { uses: ['Anti-inflammatory', 'Digestive health', 'Skin care', 'Joint health'], benefits: 'Reduces inflammation, aids digestion, improves skin complexion, and supports joint health.', partsUsed: 'Rhizome (root)', dosageInfo: 'Fresh: grate into curries and teas. Golden milk: 1 tsp turmeric powder with warm milk.', precautions: 'May act as a blood thinner. Avoid in large quantities before surgery or with blood thinners.' },
    careGuide: { wateringSchedule: 'Every 2-3 days', sunlightRequirement: 'Partial shade to bright indirect light', soilType: 'Rich, moist well-draining soil', soilChangeFrequency: 'Every 12 months at harvest', temperature: '20-35°C', humidity: '60-80%' },
    stock: 15,
    featured: false,
    ratings: { average: 4.4, count: 33 },
  },
];

const adminUser = {
  name: 'Admin',
  email: 'admin@greencart.com',
  password: 'admin123',
  role: 'admin',
};

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/greencart');
    console.log('Connected to MongoDB');

    await Plant.deleteMany({});
    await User.deleteMany({});

    await Plant.insertMany(plants);
    console.log(`${plants.length} plants inserted`);

    await User.create(adminUser);
    console.log('Admin user created (admin@greencart.com / admin123)');

    console.log('Seed completed!');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
